// <auto-generated />
using System;
using BackpackStoreFS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackpackStoreFS.Migrations
{
    [DbContext(typeof(BackpackContext))]
    [Migration("20260315173345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackpackStoreFS.Models.Entities.Backpack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("rating");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("sale_price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Backpacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Image = "/images/APEX_Commuter.png",
                            IsNew = false,
                            Name = "APEX COMMUTER",
                            Price = 90m,
                            Quantity = 10,
                            Rating = 4.5m,
                            SalePrice = 65m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Image = "/images/APEX_Heritage.png",
                            IsNew = true,
                            Name = "APEX HERITAGE",
                            Price = 75m,
                            Quantity = 12,
                            Rating = 4.1m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Image = "/images/APEX_Pulse.png",
                            IsNew = true,
                            Name = "APEX PULSE",
                            Price = 80m,
                            Quantity = 8,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Image = "/images/APEX_Stealth.png",
                            IsNew = false,
                            Name = "APEX STEALTH",
                            Price = 110m,
                            Quantity = 6,
                            Rating = 4.2m,
                            SalePrice = 95m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Image = "/images/APEX_Skyline.png",
                            IsNew = false,
                            Name = "APEX SKYLINE",
                            Price = 95m,
                            Quantity = 9,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Image = "/images/APEX_Global.png",
                            IsNew = false,
                            Name = "APEX GLOBAL",
                            Price = 120m,
                            Quantity = 5,
                            Rating = 4.5m,
                            SalePrice = 85m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Image = "/images/APEX_Crossover.png",
                            IsNew = false,
                            Name = "APEX CROSSOVER",
                            Price = 95m,
                            Quantity = 7,
                            Rating = 4.0m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Image = "/images/APEX_Executive.png",
                            IsNew = false,
                            Name = "APEX EXECUTIVE",
                            Price = 150m,
                            Quantity = 4,
                            Rating = 4.9m,
                            SalePrice = 115m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Image = "/images/APEX_Ignite.png",
                            IsNew = true,
                            Name = "APEX IGNITE",
                            Price = 85m,
                            Quantity = 11,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Image = "/images/APEX_Transformer.png",
                            IsNew = false,
                            Name = "APEX TRANSFORMER",
                            Price = 110m,
                            Quantity = 6,
                            Rating = 4.7m,
                            SalePrice = 89m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Image = "/images/APEX_Legacy.png",
                            IsNew = false,
                            Name = "APEX LEGACY",
                            Price = 85m,
                            Quantity = 10,
                            Rating = 3.9m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Image = "/images/APEX_Odyssey.png",
                            IsNew = false,
                            Name = "APEX ODYSSEY",
                            Price = 160m,
                            Quantity = 3,
                            Rating = 5.0m,
                            SalePrice = 130m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Image = "/images/APEX_Voyager.png",
                            IsNew = true,
                            Name = "APEX VOYAGER",
                            Price = 145m,
                            Quantity = 5,
                            Rating = 5.0m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Image = "/images/APEX_Summit.png",
                            IsNew = false,
                            Name = "APEX SUMMIT",
                            Price = 130m,
                            Quantity = 4,
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Image = "/images/APEX_Cyber.png",
                            IsNew = false,
                            Name = "APEX CYBER",
                            Price = 180m,
                            Quantity = 2,
                            Rating = 4.6m,
                            SalePrice = 149m
                        });
                });

            modelBuilder.Entity("BackpackStoreFS.Models.Entities.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BackpackId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BackpackId");

                    b.ToTable("BasketsItems");
                });

            modelBuilder.Entity("BackpackStoreFS.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Backpacks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Duffel Bags"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Travel Packs"
                        });
                });

            modelBuilder.Entity("BackpackStoreFS.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BackpackStoreFS.Models.Entities.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BackpackId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BackpackStoreFS.Models.Entities.Backpack", b =>
                {
                    b.HasOne("BackpackStoreFS.Models.Entities.Category", "Category")
                        .WithMany("Backpacks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BackpackStoreFS.Models.Entities.BasketItem", b =>
                {
                    b.HasOne("BackpackStoreFS.Models.Entities.Backpack", "Backpack")
                        .WithMany()
                        .HasForeignKey("BackpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Backpack");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BackpackStoreFS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BackpackStoreFS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackpackStoreFS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BackpackStoreFS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackpackStoreFS.Models.Entities.Category", b =>
                {
                    b.Navigation("Backpacks");
                });
#pragma warning restore 612, 618
        }
    }
}
